#pragma once

namespace vush::ir {
  enum struct Ext_Kind {
    // Math extensions.
    e_round,
    e_round_even,
    e_trunc,
    e_iabs,
    e_fabs,
    e_isign,
    e_fsign,
    e_floor,
    e_ceil,
    e_fract,
    e_fmod,
    e_imin,
    e_umin,
    e_fmin,
    e_imax,
    e_umax,
    e_fmax,
    e_iclamp,
    e_uclamp,
    e_fclamp,
    e_radians,
    e_degrees,
    e_fmix,
    e_step,
    e_smooth_step,
    e_fma,
    e_sin,
    e_cos,
    e_tan,
    e_asin,
    e_acos,
    e_atan,
    e_atan2,
    e_sinh,
    e_cosh,
    e_tanh,
    e_asinh,
    e_acosh,
    e_atanh,
    e_pow,
    e_exp,
    e_exp2,
    e_log,
    e_log2,
    e_sqrt,
    e_inv_sqrt,
    e_length,
    e_distance,
    e_dot,
    e_cross,
    e_normalize,
    e_faceforward,
    e_reflect,
    e_refract,
    e_mat_comp_mult,
    e_outer_product,
    e_transpose,
    e_mat_det,
    e_mat_inv,
    // Texture and image extensions.
    e_tex_size,
    e_tex_query_lod,
    e_tex_query_levels,
    e_tex_samples,
    e_tex,
    e_tex_lod,
    e_tex_proj,
    e_tex_off,
    e_texel_fetch,
    e_texel_fetch_off,
    e_tex_lod_off,
    e_tex_proj_lod_off,
    e_tex_proj_lod,
    e_tex_proj_off,
    e_tex_grad,
    e_tex_grad_off,
    e_tex_proj_grad,
    e_tex_proj_grad_off,
    e_tex_gather,
    e_tex_gather_off,
    e_tex_gather_offs,
    // Atomic extensions.
    // Derivative extensions.
    // Miscellaneous extensions.
  };
}
