from enum import Enum

from builtin_type import Builtin_Type

class Param_Type(Enum):
  ftype = Builtin_Type.type_float, Builtin_Type.type_vec2, Builtin_Type.type_vec3, Builtin_Type.type_vec4,
  dtype = Builtin_Type.type_double, Builtin_Type.type_dvec2, Builtin_Type.type_dvec3, Builtin_Type.type_dvec4,
  itype = Builtin_Type.type_int, Builtin_Type.type_ivec2, Builtin_Type.type_ivec3, Builtin_Type.type_ivec4,
  utype = Builtin_Type.type_uint, Builtin_Type.type_uvec2, Builtin_Type.type_uvec3, Builtin_Type.type_uvec4,
  btype = Builtin_Type.type_bool, Builtin_Type.type_bvec2, Builtin_Type.type_bvec3, Builtin_Type.type_bvec4,
  vecN = Builtin_Type.type_vec2, Builtin_Type.type_vec3, Builtin_Type.type_vec4,
  dvecN = Builtin_Type.type_dvec2, Builtin_Type.type_dvec3, Builtin_Type.type_dvec4,
  ivecN = Builtin_Type.type_ivec2, Builtin_Type.type_ivec3, Builtin_Type.type_ivec4,
  uvecN = Builtin_Type.type_uvec2, Builtin_Type.type_uvec3, Builtin_Type.type_uvec4,
  bvecN = Builtin_Type.type_bvec2, Builtin_Type.type_bvec3, Builtin_Type.type_bvec4,
  gvec4 = Builtin_Type.type_vec4, Builtin_Type.type_ivec4, Builtin_Type.type_uvec4,
  matN = Builtin_Type.type_mat2, Builtin_Type.type_mat3, Builtin_Type.type_mat4,
  gsampler1D = Builtin_Type.type_sampler1D, Builtin_Type.type_isampler1D, Builtin_Type.type_usampler1D,
  gsampler2D = Builtin_Type.type_sampler2D, Builtin_Type.type_isampler2D, Builtin_Type.type_usampler2D,
  gsampler3D = Builtin_Type.type_sampler3D, Builtin_Type.type_isampler3D, Builtin_Type.type_usampler3D,
  gsamplerCube = Builtin_Type.type_samplerCube, Builtin_Type.type_isamplerCube, Builtin_Type.type_usamplerCube,
  gsamplerCubeArray = Builtin_Type.type_samplerCubeArray, Builtin_Type.type_isamplerCubeArray, Builtin_Type.type_usamplerCubeArray,
  gsampler2DRect = Builtin_Type.type_sampler2DRect, Builtin_Type.type_isampler2DRect, Builtin_Type.type_usampler2DRect,
  gsampler1DArray = Builtin_Type.type_sampler1DArray, Builtin_Type.type_isampler1DArray, Builtin_Type.type_usampler1DArray,
  gsampler2DArray = Builtin_Type.type_sampler2DArray, Builtin_Type.type_isampler2DArray, Builtin_Type.type_usampler2DArray,
  gsamplerBuffer = Builtin_Type.type_samplerBuffer, Builtin_Type.type_isamplerBuffer, Builtin_Type.type_usamplerBuffer,
  gsampler2DMS = Builtin_Type.type_sampler2DMS, Builtin_Type.type_isampler2DMS, Builtin_Type.type_usampler2DMS,
  gsampler2DMSArray = Builtin_Type.type_sampler2DMSArray, Builtin_Type.type_isampler2DMSArray, Builtin_Type.type_usampler2DMSArray,
  gsubpassInput = Builtin_Type.type_subpassInput, Builtin_Type.type_isubpassInput, Builtin_Type.type_usubpassInput,
  gsubpassInputMS = Builtin_Type.type_subpassInputMS, Builtin_Type.type_isubpassInputMS, Builtin_Type.type_usubpassInputMS,
  gimage2D = Builtin_Type.type_image2D, Builtin_Type.type_iimage2D, Builtin_Type.type_uimage2D,
  gimage3D = Builtin_Type.type_image3D, Builtin_Type.type_iimage3D, Builtin_Type.type_uimage3D,
  gimageCube = Builtin_Type.type_imageCube, Builtin_Type.type_iimageCube, Builtin_Type.type_uimageCube,
  gimageBuffer = Builtin_Type.type_imageBuffer, Builtin_Type.type_iimageBuffer, Builtin_Type.type_uimageBuffer,
  gimage2DArray = Builtin_Type.type_image2DArray, Builtin_Type.type_iimage2DArray, Builtin_Type.type_uimage2DArray,
  gimageCubeArray = Builtin_Type.type_imageCubeArray, Builtin_Type.type_iimageCubeArray, Builtin_Type.type_uimageCubeArray,
  gimage1D = Builtin_Type.type_image1D, Builtin_Type.type_iimage1D, Builtin_Type.type_uimage1D,
  gimage1DArray = Builtin_Type.type_image1DArray, Builtin_Type.type_iimage1DArray, Builtin_Type.type_uimage1DArray,
  gimage2DMS = Builtin_Type.type_image2DMS, Builtin_Type.type_iimage2DMS, Builtin_Type.type_uimage2DMS,
  gimage2DMSArray = Builtin_Type.type_image2DMSArray, Builtin_Type.type_iimage2DMSArray, Builtin_Type.type_uimage2DMSArray,

class Return_Placeholder:
  pass

return_= Return_Placeholder()

class Array_Type:
  # base: str
  # size: int

  def __init__(self, base, size):
    self.base = base
    self.size = size

class Exts:
  def __init__(self, fp_ext = None, sint_ext = None, uint_ext = None):
    self.fp_ext = fp_ext
    self.sint_ext = sint_ext
    self.uint_ext = uint_ext

class Fn:
  # identifier: str
  # exts: str|Exts
  # overloads: tuple(tuple(tuple(identifier:str|Return_Placeholder, Param_Type)...))

  def __init__(self, identifier, overloads, exts = Exts()):
    self.identifier = identifier
    self.exts = exts
    self.overloads = overloads

builtin_function_definitions = (
  Fn("radians",
     exts = "radians",
     overloads = (
       ((return_, Param_Type.ftype), ("pdegrees", Param_Type.ftype)),),),
  Fn("degrees",
     exts = "degrees",
     overloads = (
       ((return_, Param_Type.ftype), ("pradians", Param_Type.ftype)),),),
  Fn("sin",
     exts = "sin",
     overloads = (
       ((return_, Param_Type.ftype), ("angle", Param_Type.ftype)),),),
  Fn("cos",
     exts = "cos",
     overloads = (
       ((return_, Param_Type.ftype), ("angle", Param_Type.ftype)),),),
  Fn("tan",
     exts = "tan",
     overloads = (
       ((return_, Param_Type.ftype), ("angle", Param_Type.ftype)),),),
  Fn("asin",
     exts = "asin",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),),),
  Fn("acos",
     exts = "acos",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),),),
  Fn("atan",
     exts = "atan",
     overloads = (
       ((return_, Param_Type.ftype), ("y", Param_Type.ftype), ("x", Param_Type.ftype)),
       ((return_, Param_Type.ftype), ("y_over_x", Param_Type.ftype)),),),
  Fn("sinh",
     exts = "sinh",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),),),
  Fn("cosh",
     exts = "cosh",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),),),
  Fn("tanh",
     exts = "tanh",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),),),
  Fn("asinh",
     exts = "asinh",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),),),
  Fn("acosh",
     exts = "acosh",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),),),
  Fn("atanh",
     exts = "atanh",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),),),
  Fn("pow",
     exts = "pow",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype), ("y", Param_Type.ftype)),),),
  Fn("exp",
     exts = "exp",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),),),
  Fn("log",
     exts = "log",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),),),
  Fn("exp2",
     exts = "exp2",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),),),
  Fn("log2",
     exts = "log2",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),),),
  Fn("sqrt",
     exts = "sqrt",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype)),),),
  Fn("inv_sqrt",
     exts = "inv_sqrt",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype))),),
  Fn("abs",
     exts = Exts(fp_ext = "fabs", sint_ext = "iabs"),
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype)),
       ((return_, Param_Type.itype), ("x", Param_Type.itype)))),
  Fn("sign",
     exts = Exts(fp_ext = "fsign", sint_ext = "isign"),
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype)),
       ((return_, Param_Type.itype), ("x", Param_Type.itype)))),
  Fn("floor",
     exts = "floor",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype))),),
  Fn("trunc",
     exts = "trunc",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype))),),
  Fn("round",
     exts = "round",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype))),),
  Fn("round_even",
     exts = "round_even",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype))),),
  Fn("ceil",
     exts = "ceil",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype))),),
  Fn("fract",
     exts = "fract",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype))),),
  Fn("mod",
     exts = "fmod",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype), ("y", Builtin_Type.type_float)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype), ("y", Builtin_Type.type_double)),
       ((return_, Param_Type.vecN), ("x", Param_Type.vecN), ("y", Param_Type.vecN)),
       ((return_, Param_Type.dvecN), ("x", Param_Type.dvecN), ("y", Param_Type.dvecN))),),
  # TODO: Temporarily disabled due to missing output parameters.
  # Fn("modf",
  #    overloads = (
  #      ((return_, Param_Type.ftype), ("x", Param_Type.ftype), ("y", Param_Type.ftype)),
  #      ((return_, Param_Type.dtype), ("x", Param_Type.dtype), ("y", Param_Type.dtype))),),
  Fn("min",
     exts = Exts(fp_ext = "fmin", sint_ext = "imin", uint_ext = "umin"),
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype), ("y", Builtin_Type.type_float)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype), ("y", Builtin_Type.type_double)),
       ((return_, Param_Type.itype), ("x", Param_Type.itype), ("y", Builtin_Type.type_int)),
       ((return_, Param_Type.utype), ("x", Param_Type.utype), ("y", Builtin_Type.type_uint)),
       ((return_, Param_Type.vecN), ("x", Param_Type.vecN), ("y", Param_Type.vecN)),
       ((return_, Param_Type.dvecN), ("x", Param_Type.dvecN), ("y", Param_Type.dvecN)),
       ((return_, Param_Type.ivecN), ("x", Param_Type.ivecN), ("y", Param_Type.ivecN)),
       ((return_, Param_Type.uvecN), ("x", Param_Type.uvecN), ("y", Param_Type.uvecN))),),
  Fn("max",
     exts = Exts(fp_ext = "fmax", sint_ext = "imax", uint_ext = "umax"),
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype), ("y", Builtin_Type.type_float)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype), ("y", Builtin_Type.type_double)),
       ((return_, Param_Type.itype), ("x", Param_Type.itype), ("y", Builtin_Type.type_int)),
       ((return_, Param_Type.utype), ("x", Param_Type.utype), ("y", Builtin_Type.type_uint)),
       ((return_, Param_Type.vecN), ("x", Param_Type.vecN), ("y", Param_Type.vecN)),
       ((return_, Param_Type.dvecN), ("x", Param_Type.dvecN), ("y", Param_Type.dvecN)),
       ((return_, Param_Type.ivecN), ("x", Param_Type.ivecN), ("y", Param_Type.ivecN)),
       ((return_, Param_Type.uvecN), ("x", Param_Type.uvecN), ("y", Param_Type.uvecN))),),
  Fn("clamp",
     exts = Exts(fp_ext = "fclamp", sint_ext = "iclamp", uint_ext = "uclamp"),
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype), ("min_val", Builtin_Type.type_float), ("max_val", Builtin_Type.type_float)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype), ("min_val", Builtin_Type.type_double), ("max_val", Builtin_Type.type_double)),
       ((return_, Param_Type.itype), ("x", Param_Type.itype), ("min_val", Builtin_Type.type_int), ("max_val", Builtin_Type.type_int)),
       ((return_, Param_Type.utype), ("x", Param_Type.utype), ("min_val", Builtin_Type.type_uint), ("max_val", Builtin_Type.type_uint))),),
  # Floating-Point Pack and Unpack Functions
    # TODO: pack/unpack functions
    # Fn("packUnorm2x16", ((return_, Builtin_Type.type_uint), ("v", Builtin_Type.type_vec2))),
    # Fn("packSnorm2x16", ((return_, Builtin_Type.type_uint), ("v", Builtin_Type.type_vec2))),
    # Fn("packUnorm4x8", ((return_, Builtin_Type.type_uint), ("v", Builtin_Type.type_vec4))),
    # Fn("packSnorm4x8", ((return_, Builtin_Type.type_uint), ("v", Builtin_Type.type_vec4))),
    # Fn("unpackUnorm2x16", ((return_, Builtin_Type.type_vec2), ("p", Builtin_Type.type_uint))),
    # Fn("unpackSnorm2x16", ((return_, Builtin_Type.type_vec2), ("p", Builtin_Type.type_uint))),
    # Fn("unpackUnorm4x8", ((return_, Builtin_Type.type_vec4), ("p", Builtin_Type.type_uint))),
    # Fn("unpackSnorm4x8", ((return_, Builtin_Type.type_vec4), ("p", Builtin_Type.type_uint))),
    # Fn("packHalf2x16", ((return_, Builtin_Type.type_uint), ("v", Builtin_Type.type_vec2))),
    # Fn("unpackHalf2x16", ((return_, Builtin_Type.type_vec2), ("v", Builtin_Type.type_uint))),
    # Fn("packDouble2x32", ((return_, Builtin_Type.type_double), ("v", Builtin_Type.type_uvec2))),
    # Fn("unpackDouble2x32", ((return_, Builtin_Type.type_uvec2), ("v", Builtin_Type.type_double))),
  # Geometric Functions
  Fn("length",
     exts = "length",
     overloads = (
       ((return_, Builtin_Type.type_float), ("x", Param_Type.ftype)),
       ((return_, Builtin_Type.type_double), ("x", Param_Type.dtype))),),
  Fn("distance",
     exts = "distance",
     overloads = (
       ((return_, Builtin_Type.type_float), ("p0", Param_Type.ftype), ("p1", Param_Type.ftype)),
       ((return_, Builtin_Type.type_double), ("p0", Param_Type.dtype), ("p1", Param_Type.dtype))),),
  Fn("dot",
     exts = "dot",
     overloads = (
       ((return_, Builtin_Type.type_float), ("x", Param_Type.ftype), ("y", Param_Type.ftype)),
       ((return_, Builtin_Type.type_double), ("x", Param_Type.dtype), ("y", Param_Type.dtype))),),
  Fn("cross",
     exts = "cross",
     overloads = (
       ((return_, Builtin_Type.type_vec3), ("x", Builtin_Type.type_vec3), ("y", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_dvec3), ("x", Builtin_Type.type_dvec3), ("y", Builtin_Type.type_dvec3))),),
  Fn("normalize",
     exts = "normalize",
     overloads = (
       ((return_, Param_Type.ftype), ("x", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("x", Param_Type.dtype))),),
  Fn("faceforward",
     exts = "faceforward",
     overloads = (
       ((return_, Param_Type.ftype), ("N", Param_Type.ftype), ("I", Param_Type.ftype), ("Nref", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("N", Param_Type.dtype), ("I", Param_Type.dtype), ("Nref", Param_Type.dtype))),),
  Fn("reflect",
     exts = "reflect",
     overloads = (
       ((return_, Param_Type.ftype), ("I", Param_Type.ftype), ("N", Param_Type.ftype)),
       ((return_, Param_Type.dtype), ("I", Param_Type.dtype), ("N", Param_Type.dtype)),
       ((return_, Param_Type.ftype), ("I", Param_Type.ftype), ("N", Param_Type.ftype), ("eta", Builtin_Type.type_float)),
       ((return_, Param_Type.dtype), ("I", Param_Type.dtype), ("N", Param_Type.dtype), ("eta", Builtin_Type.type_double))),),
  # Matrix Functions
  Fn("matrix_comp_mult",
     exts = "mat_comp_mult",
     overloads = (
       ((return_, Param_Type.matN), ("x", Param_Type.matN), ("y", Param_Type.matN)),
       ((return_, Builtin_Type.type_mat2x3), ("x", Builtin_Type.type_mat2x3), ("y", Builtin_Type.type_mat2x3)),
       ((return_, Builtin_Type.type_mat2x4), ("x", Builtin_Type.type_mat2x4), ("y", Builtin_Type.type_mat2x4)),
       ((return_, Builtin_Type.type_mat3x2), ("x", Builtin_Type.type_mat3x2), ("y", Builtin_Type.type_mat3x2)),
       ((return_, Builtin_Type.type_mat3x4), ("x", Builtin_Type.type_mat3x4), ("y", Builtin_Type.type_mat3x4)),
       ((return_, Builtin_Type.type_mat4x2), ("x", Builtin_Type.type_mat4x2), ("y", Builtin_Type.type_mat4x2)),
       ((return_, Builtin_Type.type_mat4x3), ("x", Builtin_Type.type_mat4x3), ("y", Builtin_Type.type_mat4x3))),),
  Fn("outer_product",
     exts = "outer_product",
     overloads = (
       ((return_, Param_Type.matN), ("c", Param_Type.vecN), ("r", Param_Type.vecN)),
       ((return_, Builtin_Type.type_mat2x3), ("c", Builtin_Type.type_vec3), ("r", Builtin_Type.type_vec2)),
       ((return_, Builtin_Type.type_mat3x2), ("c", Builtin_Type.type_vec2), ("r", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_mat2x4), ("c", Builtin_Type.type_vec4), ("r", Builtin_Type.type_vec2)),
       ((return_, Builtin_Type.type_mat4x2), ("c", Builtin_Type.type_vec2), ("r", Builtin_Type.type_vec4)),
       ((return_, Builtin_Type.type_mat3x4), ("c", Builtin_Type.type_vec4), ("r", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_mat4x3), ("c", Builtin_Type.type_vec3), ("r", Builtin_Type.type_vec4))),),
  Fn("transpose",
     exts = "transpose",
     overloads = (
       ((return_, Param_Type.matN), ("m", Param_Type.matN)),
       ((return_, Builtin_Type.type_mat2x3), ("m", Builtin_Type.type_mat3x2)),
       ((return_, Builtin_Type.type_mat3x2), ("m", Builtin_Type.type_mat2x3)),
       ((return_, Builtin_Type.type_mat2x4), ("m", Builtin_Type.type_mat4x2)),
       ((return_, Builtin_Type.type_mat4x2), ("m", Builtin_Type.type_mat2x4)),
       ((return_, Builtin_Type.type_mat3x4), ("m", Builtin_Type.type_mat4x3)),
       ((return_, Builtin_Type.type_mat4x3), ("m", Builtin_Type.type_mat3x4))),),
  Fn("determinant",
     exts = "mat_det",
     overloads = (
       ((return_, Builtin_Type.type_float), ("m", Param_Type.matN)),),),
  Fn("inverse",
     exts = "mat_inv",
     overloads = (
       ((return_, Param_Type.matN), ("m", Param_Type.matN)),),),
  # Vector Relational Functions
  Fn("less_than",
     overloads = (
       ((return_, Param_Type.bvecN), ("x", Param_Type.vecN), ("y", Param_Type.vecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.dvecN), ("y", Param_Type.dvecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.ivecN), ("y", Param_Type.ivecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.uvecN), ("y", Param_Type.uvecN))),),
  Fn("less_than_equal",
     overloads = (
       ((return_, Param_Type.bvecN), ("x", Param_Type.vecN), ("y", Param_Type.vecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.dvecN), ("y", Param_Type.dvecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.ivecN), ("y", Param_Type.ivecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.uvecN), ("y", Param_Type.uvecN))),),
  Fn("greater_than",
     overloads = (
       ((return_, Param_Type.bvecN), ("x", Param_Type.vecN), ("y", Param_Type.vecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.dvecN), ("y", Param_Type.dvecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.ivecN), ("y", Param_Type.ivecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.uvecN), ("y", Param_Type.uvecN))),),
  Fn("greater_than_equal",
     overloads = (
       ((return_, Param_Type.bvecN), ("x", Param_Type.vecN), ("y", Param_Type.vecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.dvecN), ("y", Param_Type.dvecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.ivecN), ("y", Param_Type.ivecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.uvecN), ("y", Param_Type.uvecN))),),
  Fn("equal",
     overloads = (
       ((return_, Param_Type.bvecN), ("x", Param_Type.vecN), ("y", Param_Type.vecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.dvecN), ("y", Param_Type.dvecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.ivecN), ("y", Param_Type.ivecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.uvecN), ("y", Param_Type.uvecN))),),
  Fn("not_equal",
     overloads = (
       ((return_, Param_Type.bvecN), ("x", Param_Type.vecN), ("y", Param_Type.vecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.dvecN), ("y", Param_Type.dvecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.ivecN), ("y", Param_Type.ivecN)),
       ((return_, Param_Type.bvecN), ("x", Param_Type.uvecN), ("y", Param_Type.uvecN))),),
  Fn("any",
     overloads = (
       ((return_, Builtin_Type.type_bool), ("x", Param_Type.bvecN)),),),
  Fn("all",
     overloads = (
       ((return_, Builtin_Type.type_bool), ("x", Param_Type.bvecN)),),),
  Fn("not",
     overloads = (
       ((return_, Param_Type.bvecN), ("x", Param_Type.bvecN)),),),
  # Integer Functions
  Fn("uadd_carry",
     overloads = (
       ((return_, Param_Type.utype), ("x", Param_Type.utype), ("y", Param_Type.utype), ("carry", Param_Type.utype)),),),
  Fn("usub_borrow",
     overloads = (
       ((return_, Param_Type.utype), ("x", Param_Type.utype), ("y", Param_Type.utype), ("borrow", Param_Type.utype)),),),
  Fn("umul_extended",
     overloads = (
       ((return_, Builtin_Type.type_void), ("x", Param_Type.utype), ("y", Param_Type.utype), ("msb", Param_Type.utype), ("lsb", Param_Type.utype)),),),
  Fn("imul_extended",
     overloads = (
       ((return_, Builtin_Type.type_void), ("x", Param_Type.itype), ("y", Param_Type.itype), ("msb", Param_Type.itype), ("lsb", Param_Type.itype)),),),
  Fn("bitfield_extract",
     overloads = (
       ((return_, Builtin_Type.type_void), ("value", Param_Type.itype), ("offset", Builtin_Type.type_int), ("bits", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_void), ("value", Param_Type.utype), ("offset", Builtin_Type.type_int), ("bits", Builtin_Type.type_int)),),),
  Fn("bitfield_insert",
     overloads = (
       ((return_, Builtin_Type.type_void), ("base", Param_Type.itype), ("insert", Param_Type.itype), ("offset", Builtin_Type.type_int), ("bits", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_void), ("base", Param_Type.utype), ("insert", Param_Type.utype), ("offset", Builtin_Type.type_int), ("bits", Builtin_Type.type_int)),),),
  Fn("bitfield_reverse",
     overloads = (
       ((return_, Builtin_Type.type_void), ("base", Param_Type.itype)),
       ((return_, Builtin_Type.type_void), ("base", Param_Type.utype)),),),
  Fn("bit_count",
     overloads = (
       ((return_, Builtin_Type.type_void), ("base", Param_Type.itype)),
       ((return_, Builtin_Type.type_void), ("base", Param_Type.utype)),),),
  Fn("find_LSB",
     overloads = (
      ((return_, Builtin_Type.type_void), ("base", Param_Type.itype)),
      ((return_, Builtin_Type.type_void), ("base", Param_Type.utype)),),),
  Fn("find_MSB",
     overloads = (
      ((return_, Builtin_Type.type_void), ("base", Param_Type.itype)),
      ((return_, Builtin_Type.type_void), ("base", Param_Type.utype)),),),
  # Texture Query Functions
  Fn("texture_size",
     exts = "tex_size",
     overloads = (
       ((return_, Builtin_Type.type_int), ("sampler", Param_Type.gsampler1D), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_ivec2), ("sampler", Param_Type.gsampler2D), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_ivec3), ("sampler", Param_Type.gsampler3D), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_ivec2), ("sampler", Param_Type.gsamplerCube), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("sampler", Builtin_Type.type_sampler1DShadow), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_ivec2), ("sampler", Builtin_Type.type_sampler2DShadow), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_ivec2), ("sampler", Builtin_Type.type_samplerCubeShadow), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_ivec3), ("sampler", Param_Type.gsamplerCubeArray), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_ivec3), ("sampler", Builtin_Type.type_samplerCubeArrayShadow), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_ivec2), ("sampler", Param_Type.gsampler1DArray), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_ivec2), ("sampler", Builtin_Type.type_sampler1DArrayShadow), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_ivec3), ("sampler", Param_Type.gsampler2DArray), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_ivec3), ("sampler", Builtin_Type.type_sampler2DArrayShadow), ("lod", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_ivec3), ("sampler", Param_Type.gsampler2DRect)),
       ((return_, Builtin_Type.type_ivec2), ("sampler", Builtin_Type.type_sampler2DRectShadow)),
       ((return_, Builtin_Type.type_int), ("sampler", Param_Type.gsamplerBuffer)),
       ((return_, Builtin_Type.type_ivec2), ("sampler", Param_Type.gsampler2DMS)),
       ((return_, Builtin_Type.type_ivec3), ("sampler", Param_Type.gsampler2DMSArray))),),
  Fn("texture_query_lod",
     exts = "tex_query_lod",
     overloads = (
       ((return_, Builtin_Type.type_vec2), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_vec2), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2)),
       ((return_, Builtin_Type.type_vec2), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_vec2), ("sampler", Param_Type.gsamplerCube), ("P", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_vec2), ("sampler", Param_Type.gsampler1DArray), ("P", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_vec2), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec2)),
       ((return_, Builtin_Type.type_vec2), ("sampler", Param_Type.gsamplerCubeArray), ("P", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_vec2), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_vec2), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec2)),
       ((return_, Builtin_Type.type_vec2), ("sampler", Builtin_Type.type_samplerCubeShadow), ("P", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_vec2), ("sampler", Builtin_Type.type_sampler1DArrayShadow), ("P", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_vec2), ("sampler", Builtin_Type.type_sampler2DArrayShadow), ("P", Builtin_Type.type_vec2)),
       ((return_, Builtin_Type.type_vec2), ("sampler", Builtin_Type.type_samplerCubeArrayShadow), ("P", Builtin_Type.type_vec3))),),
  Fn("texture_query_levels",
     exts = "tex_query_levels",
     overloads = (
       ((return_, Builtin_Type.type_int), ("sampler", Param_Type.gsampler1D)),
       ((return_, Builtin_Type.type_int), ("sampler", Param_Type.gsampler2D)),
       ((return_, Builtin_Type.type_int), ("sampler", Param_Type.gsampler3D)),
       ((return_, Builtin_Type.type_int), ("sampler", Param_Type.gsamplerCube)),
       ((return_, Builtin_Type.type_int), ("sampler", Param_Type.gsampler1DArray)),
       ((return_, Builtin_Type.type_int), ("sampler", Param_Type.gsampler2DArray)),
       ((return_, Builtin_Type.type_int), ("sampler", Param_Type.gsamplerCubeArray)),
       ((return_, Builtin_Type.type_int), ("sampler", Builtin_Type.type_sampler1DShadow)),
       ((return_, Builtin_Type.type_int), ("sampler", Builtin_Type.type_sampler2DShadow)),
       ((return_, Builtin_Type.type_int), ("sampler", Builtin_Type.type_samplerCubeShadow)),
       ((return_, Builtin_Type.type_int), ("sampler", Builtin_Type.type_sampler1DArrayShadow)),
       ((return_, Builtin_Type.type_int), ("sampler", Builtin_Type.type_sampler2DArrayShadow)),
       ((return_, Builtin_Type.type_int), ("sampler", Builtin_Type.type_samplerCubeArrayShadow))),),
  Fn("texture_samples",
     exts = "tex_samples",
     overloads = (
       ((return_, Builtin_Type.type_int), ("sampler", Param_Type.gsampler2DMS)),
       ((return_, Builtin_Type.type_int), ("sampler", Param_Type.gsampler2DMSArray))),),
  # Texture Lookup Functions
  Fn("texture",
     exts = "tex",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_float), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec3), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerCube), ("P", Builtin_Type.type_vec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerCube), ("P", Builtin_Type.type_vec3), ("bias", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec3), ("bias", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec3), ("bias", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_samplerCubeShadow), ("P", Builtin_Type.type_vec4)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_samplerCubeShadow), ("P", Builtin_Type.type_vec4), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerCubeArray), ("P", Builtin_Type.type_vec4)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerCubeArray), ("P", Builtin_Type.type_vec4), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1DArray), ("P", Builtin_Type.type_vec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1DArray), ("P", Builtin_Type.type_vec2), ("bias", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DArrayShadow), ("P", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DArrayShadow), ("P", Builtin_Type.type_vec3), ("bias", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DArrayShadow), ("P", Builtin_Type.type_vec4)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DRectShadow), ("P", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_samplerCubeArrayShadow), ("P", Builtin_Type.type_vec4), ("compare", Builtin_Type.type_float))),),
  Fn("texture_proj",
     exts = "tex_proj",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec2), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec4)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec4), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec3), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec4)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec4), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec4)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec4), ("bias", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec4)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec4), ("bias", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec4)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec4), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec4)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DRectShadow), ("P", Builtin_Type.type_vec4))),),
  Fn("texture_lod",
     exts = "tex_lod",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_float), ("lod", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2), ("lod", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerCube), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1DArray), ("P", Builtin_Type.type_vec2), ("lod", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DArrayShadow), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerCubeArray), ("P", Builtin_Type.type_vec4), ("lod", Builtin_Type.type_float))),),
  Fn("texture_offset",
     exts = "tex_off",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_float), ("offset", Builtin_Type.type_int), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec3), ("bias", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec2), ("bias", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_int), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1DArray), ("P", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1DArray), ("P", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_int), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec2), ("bias", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DArrayShadow), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DArrayShadow), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_int), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DRectShadow), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DArrayShadow), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_ivec2))),),
  Fn("texel_fetch",
     exts = "texel_fetch",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_ivec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1DArray), ("P", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_ivec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_ivec2), ("lod", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerBuffer), ("P", Builtin_Type.type_int), ("lod", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int))),),
  Fn("texel_fetch_offset",
     exts = "texel_fetch_off",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_int), ("lod", Builtin_Type.type_int), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_ivec2), ("lod", Builtin_Type.type_int), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_ivec3), ("lod", Builtin_Type.type_int), ("offset", Builtin_Type.type_ivec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1DArray), ("P", Builtin_Type.type_ivec2), ("lod", Builtin_Type.type_int), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_ivec3), ("lod", Builtin_Type.type_int), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_ivec2), ("offset", Builtin_Type.type_ivec2))),),
  Fn("texture_proj_offset",
     exts = "tex_proj_off",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_int), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_int), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec2), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_ivec2), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_ivec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_ivec3), ("bias", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_int), ("bias", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_ivec2), ("bias", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DRectShadow), ("P", Builtin_Type.type_vec4), ("offset", Builtin_Type.type_ivec2))),),
  Fn("texture_lod_offset",
     exts = "tex_lod_off",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_float), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_ivec3)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1DArray), ("P", Builtin_Type.type_vec2), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DArrayShadow), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_int))),),
  Fn("texture_proj_lod",
     exts = "tex_proj_lod",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec2), ("lod", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec4), ("lod", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec4), ("lod", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec4), ("lod", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec4), ("lod", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec4), ("lod", Builtin_Type.type_float))),),
  Fn("texture_proj_lod_offset",
     exts = "tex_proj_lod_off",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec2), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec4), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec3), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec4), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec4), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_ivec3)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec4), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec4), ("lod", Builtin_Type.type_float), ("offset", Builtin_Type.type_ivec2))),),
  Fn("texture_grad",
     exts = "tex_grad",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_float), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec3), ("dPdy", Builtin_Type.type_vec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerCube), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec3), ("dPdy", Builtin_Type.type_vec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec2), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1DArray), ("P", Builtin_Type.type_vec2), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerCubeArray), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec3), ("dPdy", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DRectShadow), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DArrayShadow), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_samplerCubeShadow), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec3), ("dPdy", Builtin_Type.type_vec3)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DArrayShadow), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2))),),
  Fn("texture_grad_offset",
     exts = "tex_grad_off",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_float), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec3), ("dPdy", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec2), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1DArray), ("P", Builtin_Type.type_vec2), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DRectShadow), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DArrayShadow), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DArrayShadow), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2))),),
  Fn("texture_proj_grad",
     exts = "tex_proj_grad",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec2), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec3), ("dPdy", Builtin_Type.type_vec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DRectShadow), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2))),),
  Fn("texture_proj_grad_offset",
     exts = "tex_proj_grad_off",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec2), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler1D), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler3D), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec3), ("dPdy", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec3), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DRectShadow), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler1DShadow), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_float), ("dPdy", Builtin_Type.type_float), ("offset", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_float), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec4), ("dPdx", Builtin_Type.type_vec2), ("dPdy", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2))),),
  # Texture Gather Functions
  Fn("texture_gather",
     exts = "tex_gather",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2), ("comp", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3), ("comp", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerCube), ("P", Builtin_Type.type_vec3)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerCube), ("P", Builtin_Type.type_vec3), ("comp", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerCubeArray), ("P", Builtin_Type.type_vec4)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsamplerCubeArray), ("P", Builtin_Type.type_vec4), ("comp", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec2), ("comp", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_vec4), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec2), ("refZ", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_vec4), ("sampler", Builtin_Type.type_sampler2DArrayShadow), ("P", Builtin_Type.type_vec3), ("refZ", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_vec4), ("sampler", Builtin_Type.type_samplerCubeShadow), ("P", Builtin_Type.type_vec3), ("refZ", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_vec4), ("sampler", Builtin_Type.type_samplerCubeArrayShadow), ("P", Builtin_Type.type_vec4), ("refZ", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_vec4), ("sampler", Builtin_Type.type_sampler2DRectShadow), ("P", Builtin_Type.type_vec2), ("refZ", Builtin_Type.type_float))),),
  Fn("texture_gather_offset",
     exts = "tex_gather_off",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2), ("comp", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3), ("offset", Builtin_Type.type_ivec2), ("comp", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec2), ("offset", Builtin_Type.type_ivec2), ("comp", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_vec4), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec2), ("refZ", Builtin_Type.type_float), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Builtin_Type.type_vec4), ("sampler", Builtin_Type.type_sampler2DArrayShadow), ("P", Builtin_Type.type_vec3), ("refZ", Builtin_Type.type_float), ("offset", Builtin_Type.type_ivec2)),
       ((return_, Builtin_Type.type_vec4), ("sampler", Builtin_Type.type_sampler2DRectShadow), ("P", Builtin_Type.type_vec2), ("refZ", Builtin_Type.type_float), ("offset", Builtin_Type.type_ivec2))),),
  Fn("texture_gather_offsets",
     exts = "tex_gather_offs",
     overloads = (
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2), ("offsets", Array_Type(Builtin_Type.type_ivec2, 4))),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2D), ("P", Builtin_Type.type_vec2), ("offsets", Array_Type(Builtin_Type.type_ivec2, 4)), ("comp", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3), ("offsets", Array_Type(Builtin_Type.type_ivec2, 4))),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DArray), ("P", Builtin_Type.type_vec3), ("offsets", Array_Type(Builtin_Type.type_ivec2, 4)), ("comp", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec2), ("offsets", Array_Type(Builtin_Type.type_ivec2, 4))),
       ((return_, Param_Type.gvec4), ("sampler", Param_Type.gsampler2DRect), ("P", Builtin_Type.type_vec2), ("offsets", Array_Type(Builtin_Type.type_ivec2, 4)), ("comp", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_vec4), ("sampler", Builtin_Type.type_sampler2DShadow), ("P", Builtin_Type.type_vec2), ("refZ", Builtin_Type.type_float), ("offsets", Array_Type(Builtin_Type.type_ivec2, 4))),
       ((return_, Builtin_Type.type_vec4), ("sampler", Builtin_Type.type_sampler2DArrayShadow), ("P", Builtin_Type.type_vec3), ("refZ", Builtin_Type.type_float), ("offsets", Array_Type(Builtin_Type.type_ivec2, 4))),
       ((return_, Builtin_Type.type_vec4), ("sampler", Builtin_Type.type_sampler2DRectShadow), ("P", Builtin_Type.type_vec2), ("refZ", Builtin_Type.type_float), ("offsets", Array_Type(Builtin_Type.type_ivec2, 4)))),),
  # Atomic Memory Functions
  Fn("atomic_add",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_int), ("mem", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_uint), ("mem", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint))),),
  Fn("atomic_min",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_int), ("mem", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_uint), ("mem", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint))),),
  Fn("atomic_max",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_int), ("mem", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_uint), ("mem", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint))),),
  Fn("atomic_and",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_int), ("mem", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_uint), ("mem", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint))),),
  Fn("atomic_or",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_int), ("mem", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_uint), ("mem", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint))),),
  Fn("atomic_xor",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_int), ("mem", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_uint), ("mem", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint))),),
  Fn("atomic_exchange",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_int), ("mem", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_uint), ("mem", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint))),),
  Fn("atomic_comp_swap",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_int), ("mem", Builtin_Type.type_int), ("compare", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_uint), ("mem", Builtin_Type.type_uint), ("compare", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint))),),
  # Image Functions
  Fn("image_size",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1D)),
       ((return_, Builtin_Type.type_ivec2), ("image", Param_Type.gimage2D)),
       ((return_, Builtin_Type.type_ivec3), ("image", Param_Type.gimage3D)),
       ((return_, Builtin_Type.type_ivec2), ("image", Param_Type.gimageCube)),
       ((return_, Builtin_Type.type_ivec3), ("image", Param_Type.gimageCubeArray)),
       ((return_, Builtin_Type.type_ivec3), ("image", Param_Type.gimage2DArray)),
       ((return_, Builtin_Type.type_ivec2), ("image", Param_Type.gimage1DArray)),
       ((return_, Builtin_Type.type_ivec2), ("image", Param_Type.gimage2DMS)),
       ((return_, Builtin_Type.type_ivec3), ("image", Param_Type.gimage2DMSArray)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageBuffer))),),
  Fn("image_samples",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMS)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMSArray))),),
  Fn("image_load",
     exts = Exts(),
     overloads = (
       ((return_, Param_Type.gvec4), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3)),
       ((return_, Param_Type.gvec4), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3)),
       ((return_, Param_Type.gvec4), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3)),
       ((return_, Param_Type.gvec4), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3)),
       ((return_, Param_Type.gvec4), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2)),
       ((return_, Param_Type.gvec4), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int)),
       ((return_, Param_Type.gvec4), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int))),),
  Fn("image_store",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_void), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Param_Type.gvec4)),
       ((return_, Builtin_Type.type_void), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Param_Type.gvec4)),
       ((return_, Builtin_Type.type_void), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Param_Type.gvec4)),
       ((return_, Builtin_Type.type_void), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Param_Type.gvec4)),
       ((return_, Builtin_Type.type_void), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Param_Type.gvec4)),
       ((return_, Builtin_Type.type_void), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Param_Type.gvec4)),
       ((return_, Builtin_Type.type_void), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Param_Type.gvec4)),
       ((return_, Builtin_Type.type_void), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Param_Type.gvec4)),
       ((return_, Builtin_Type.type_void), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_int), ("sample", Builtin_Type.type_ivec2), ("data", Param_Type.gvec4)),
       ((return_, Builtin_Type.type_void), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_int), ("sample", Builtin_Type.type_ivec3), ("data", Param_Type.gvec4))),),
  Fn("image_atomic_add",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int))),),
  Fn("image_atomic_min",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int))),),
  Fn("image_atomic_max",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int))),),
  Fn("image_atomic_and",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int))),),
  Fn("image_atomic_or",
     overloads = (
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int))),),
  Fn("image_atomic_xor",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int))),),
  Fn("image_atomic_exchange",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_float), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("data", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("data", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("data", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_float)),
       ((return_, Builtin_Type.type_float), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("data", Builtin_Type.type_float))),),
  Fn("image_atomic_comp_swap",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("compare", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("compare", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("compare", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("compare", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("compare", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("compare", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("compare", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("compare", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("compare", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_uint), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("compare", Builtin_Type.type_uint), ("data", Builtin_Type.type_uint)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2D), ("P", Builtin_Type.type_ivec2), ("compare", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage3D), ("P", Builtin_Type.type_ivec3), ("compare", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCube), ("P", Builtin_Type.type_ivec3), ("compare", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageBuffer), ("P", Builtin_Type.type_int), ("compare", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DArray), ("P", Builtin_Type.type_ivec3), ("compare", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimageCubeArray), ("P", Builtin_Type.type_ivec3), ("compare", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1D), ("P", Builtin_Type.type_int), ("compare", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage1DArray), ("P", Builtin_Type.type_ivec2), ("compare", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMS), ("P", Builtin_Type.type_ivec2), ("sample", Builtin_Type.type_int), ("compare", Builtin_Type.type_int), ("data", Builtin_Type.type_int)),
       ((return_, Builtin_Type.type_int), ("image", Param_Type.gimage2DMSArray), ("P", Builtin_Type.type_ivec3), ("sample", Builtin_Type.type_int), ("compare", Builtin_Type.type_int), ("data", Builtin_Type.type_int))),),
  # Fragment Derivative Functions
  Fn("dFdx",
     exts = Exts(),
     overloads = (
       ((return_, Param_Type.ftype), ("p", Param_Type.ftype)),),),
  Fn("dFdy",
     exts = Exts(),
     overloads = (
       ((return_, Param_Type.ftype), ("p", Param_Type.ftype)),),),
  Fn("dFdx_fine",
     exts = Exts(),
     overloads = (
       ((return_, Param_Type.ftype), ("p", Param_Type.ftype)),),),
  Fn("dFdy_fine",
     exts = Exts(),
     overloads = (
       ((return_, Param_Type.ftype), ("p", Param_Type.ftype)),),),
  Fn("dFdx_coarse",
     exts = Exts(),
     overloads = (
       ((return_, Param_Type.ftype), ("p", Param_Type.ftype)),),),
  Fn("dFdy_coarse",
     exts = Exts(),
     overloads = (
       ((return_, Param_Type.ftype), ("p", Param_Type.ftype)),),),
  Fn("fwidth",
     exts = Exts(),
     overloads = (((return_, Param_Type.ftype), ("p", Param_Type.ftype)),),),
  Fn("fwidth_fine",
     exts = Exts(),
     overloads = (
       ((return_, Param_Type.ftype), ("p", Param_Type.ftype)),),),
  Fn("fwidth_coarse",
     exts = Exts(),
     overloads = (
       ((return_, Param_Type.ftype), ("p", Param_Type.ftype)),),),
  # Fragment Interpolation Functions
  Fn("interpolate_at_centroid",
     exts = Exts(),
     overloads = (
       ((return_, Param_Type.ftype), ("interpolant", Param_Type.ftype)),),),
  Fn("interpolate_at_sample",
     exts = Exts(),
     overloads = (
       ((return_, Param_Type.ftype), ("interpolant", Param_Type.ftype), ("sample", Builtin_Type.type_int)),),),
  Fn("interpolate_at_offset",
     exts = Exts(),
     overloads = (
       ((return_, Param_Type.ftype), ("interpolant", Param_Type.ftype), ("offset", Builtin_Type.type_vec2)),),),
  # Shader Invocation Control Functions
  Fn("barrier",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_void),),),),
  # Shader Memory Control Functions
  Fn("memory_barrier",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_void),),),),
  Fn("memory_barrier_atomic_counter",
     exts = Exts(),
     overloads = (
       ((return_, Builtin_Type.type_void),),),),
  Fn("memory_barrier_buffer",
     overloads = (
       ((return_, Builtin_Type.type_void),),),),
  Fn("memory_barrier_shared",
     overloads = (
       ((return_, Builtin_Type.type_void),),),),
  Fn("memory_barrier_image",
     overloads = (
       ((return_, Builtin_Type.type_void),),),),
  Fn("group_memory_barrier",
     overloads = (
       ((return_, Builtin_Type.type_void),),),),
  # Subpass-Input Functions
  Fn("subpass_load",
     overloads = (
       ((return_, Param_Type.gvec4), ("subpass", Param_Type.gsubpassInput)),
       ((return_, Param_Type.gvec4), ("subpass", Param_Type.gsubpassInputMS), ("sample", Builtin_Type.type_int)))),
  # Shader Invocation Group Functions
  Fn("any_invocation",
     overloads = (
       ((return_, Builtin_Type.type_bool), ("value", Builtin_Type.type_bool)),),),
  Fn("all_invocations",
     overloads = (
       ((return_, Builtin_Type.type_bool), ("value", Builtin_Type.type_bool)),),),
  Fn("all_invocations_equal",
     overloads = (
       ((return_, Builtin_Type.type_bool), ("value", Builtin_Type.type_bool)),),),
)
