from builtin_type import Builtin_Type

class Builtin_Operator:
    # identifier
    # signature (return type, parameter type...)

    def __init__(self, identifier, signature):
        self.identifier = identifier
        self.signature = signature

builtin_operator_definitions = (
    # Two operands are scalars.
    Builtin_Operator("operator+", (Builtin_Type.type_int, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator+", (Builtin_Type.type_uint, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator+", (Builtin_Type.type_float, Builtin_Type.type_float, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_double, Builtin_Type.type_double, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_int, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator-", (Builtin_Type.type_uint, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator-", (Builtin_Type.type_float, Builtin_Type.type_float, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_double, Builtin_Type.type_double, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_int, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator*", (Builtin_Type.type_uint, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator*", (Builtin_Type.type_float, Builtin_Type.type_float, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_double, Builtin_Type.type_double, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_int, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator/", (Builtin_Type.type_uint, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator/", (Builtin_Type.type_float, Builtin_Type.type_float, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_double, Builtin_Type.type_double, Builtin_Type.type_double)),
    # One operand is a scalar and the other is a vector or matrix.
    Builtin_Operator("operator+", (Builtin_Type.type_vec2, Builtin_Type.type_vec2, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_vec3, Builtin_Type.type_vec3, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_vec4, Builtin_Type.type_vec4, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_vec2, Builtin_Type.type_float, Builtin_Type.type_vec2)),
    Builtin_Operator("operator+", (Builtin_Type.type_vec3, Builtin_Type.type_float, Builtin_Type.type_vec3)),
    Builtin_Operator("operator+", (Builtin_Type.type_vec4, Builtin_Type.type_float, Builtin_Type.type_vec4)),
    Builtin_Operator("operator+", (Builtin_Type.type_dvec2, Builtin_Type.type_dvec2, Builtin_Type.type_double)),
    Builtin_Operator("operator+", (Builtin_Type.type_dvec3, Builtin_Type.type_dvec3, Builtin_Type.type_double)),
    Builtin_Operator("operator+", (Builtin_Type.type_dvec4, Builtin_Type.type_dvec4, Builtin_Type.type_double)),
    Builtin_Operator("operator+", (Builtin_Type.type_dvec2, Builtin_Type.type_double, Builtin_Type.type_dvec2)),
    Builtin_Operator("operator+", (Builtin_Type.type_dvec3, Builtin_Type.type_double, Builtin_Type.type_dvec3)),
    Builtin_Operator("operator+", (Builtin_Type.type_dvec4, Builtin_Type.type_double, Builtin_Type.type_dvec4)),
    Builtin_Operator("operator+", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_int)),
    Builtin_Operator("operator+", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_int)),
    Builtin_Operator("operator+", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_int)),
    Builtin_Operator("operator+", (Builtin_Type.type_ivec2, Builtin_Type.type_int, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator+", (Builtin_Type.type_ivec3, Builtin_Type.type_int, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator+", (Builtin_Type.type_ivec4, Builtin_Type.type_int, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator+", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uint)),
    Builtin_Operator("operator+", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uint)),
    Builtin_Operator("operator+", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uint)),
    Builtin_Operator("operator+", (Builtin_Type.type_uvec2, Builtin_Type.type_uint, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator+", (Builtin_Type.type_uvec3, Builtin_Type.type_uint, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator+", (Builtin_Type.type_uvec4, Builtin_Type.type_uint, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator-", (Builtin_Type.type_vec2, Builtin_Type.type_vec2, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_vec3, Builtin_Type.type_vec3, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_vec4, Builtin_Type.type_vec4, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_vec2, Builtin_Type.type_float, Builtin_Type.type_vec2)),
    Builtin_Operator("operator-", (Builtin_Type.type_vec3, Builtin_Type.type_float, Builtin_Type.type_vec3)),
    Builtin_Operator("operator-", (Builtin_Type.type_vec4, Builtin_Type.type_float, Builtin_Type.type_vec4)),
    Builtin_Operator("operator-", (Builtin_Type.type_dvec2, Builtin_Type.type_dvec2, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_dvec3, Builtin_Type.type_dvec3, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_dvec4, Builtin_Type.type_dvec4, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_dvec2, Builtin_Type.type_double, Builtin_Type.type_dvec2)),
    Builtin_Operator("operator-", (Builtin_Type.type_dvec3, Builtin_Type.type_double, Builtin_Type.type_dvec3)),
    Builtin_Operator("operator-", (Builtin_Type.type_dvec4, Builtin_Type.type_double, Builtin_Type.type_dvec4)),
    Builtin_Operator("operator-", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_int)),
    Builtin_Operator("operator-", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_int)),
    Builtin_Operator("operator-", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_int)),
    Builtin_Operator("operator-", (Builtin_Type.type_ivec2, Builtin_Type.type_int, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator-", (Builtin_Type.type_ivec3, Builtin_Type.type_int, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator-", (Builtin_Type.type_ivec4, Builtin_Type.type_int, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator-", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uint)),
    Builtin_Operator("operator-", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uint)),
    Builtin_Operator("operator-", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uint)),
    Builtin_Operator("operator-", (Builtin_Type.type_uvec2, Builtin_Type.type_uint, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator-", (Builtin_Type.type_uvec3, Builtin_Type.type_uint, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator-", (Builtin_Type.type_uvec4, Builtin_Type.type_uint, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec2, Builtin_Type.type_vec2, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec3, Builtin_Type.type_vec3, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec4, Builtin_Type.type_vec4, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec2, Builtin_Type.type_float, Builtin_Type.type_vec2)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec3, Builtin_Type.type_float, Builtin_Type.type_vec3)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec4, Builtin_Type.type_float, Builtin_Type.type_vec4)),
    Builtin_Operator("operator*", (Builtin_Type.type_dvec2, Builtin_Type.type_dvec2, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_dvec3, Builtin_Type.type_dvec3, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_dvec4, Builtin_Type.type_dvec4, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_dvec2, Builtin_Type.type_double, Builtin_Type.type_dvec2)),
    Builtin_Operator("operator*", (Builtin_Type.type_dvec3, Builtin_Type.type_double, Builtin_Type.type_dvec3)),
    Builtin_Operator("operator*", (Builtin_Type.type_dvec4, Builtin_Type.type_double, Builtin_Type.type_dvec4)),
    Builtin_Operator("operator*", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_int)),
    Builtin_Operator("operator*", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_int)),
    Builtin_Operator("operator*", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_int)),
    Builtin_Operator("operator*", (Builtin_Type.type_ivec2, Builtin_Type.type_int, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator*", (Builtin_Type.type_ivec3, Builtin_Type.type_int, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator*", (Builtin_Type.type_ivec4, Builtin_Type.type_int, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator*", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uint)),
    Builtin_Operator("operator*", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uint)),
    Builtin_Operator("operator*", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uint)),
    Builtin_Operator("operator*", (Builtin_Type.type_uvec2, Builtin_Type.type_uint, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator*", (Builtin_Type.type_uvec3, Builtin_Type.type_uint, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator*", (Builtin_Type.type_uvec4, Builtin_Type.type_uint, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator/", (Builtin_Type.type_vec2, Builtin_Type.type_vec2, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_vec3, Builtin_Type.type_vec3, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_vec4, Builtin_Type.type_vec4, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_vec2, Builtin_Type.type_float, Builtin_Type.type_vec2)),
    Builtin_Operator("operator/", (Builtin_Type.type_vec3, Builtin_Type.type_float, Builtin_Type.type_vec3)),
    Builtin_Operator("operator/", (Builtin_Type.type_vec4, Builtin_Type.type_float, Builtin_Type.type_vec4)),
    Builtin_Operator("operator/", (Builtin_Type.type_dvec2, Builtin_Type.type_dvec2, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_dvec3, Builtin_Type.type_dvec3, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_dvec4, Builtin_Type.type_dvec4, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_dvec2, Builtin_Type.type_double, Builtin_Type.type_dvec2)),
    Builtin_Operator("operator/", (Builtin_Type.type_dvec3, Builtin_Type.type_double, Builtin_Type.type_dvec3)),
    Builtin_Operator("operator/", (Builtin_Type.type_dvec4, Builtin_Type.type_double, Builtin_Type.type_dvec4)),
    Builtin_Operator("operator/", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_int)),
    Builtin_Operator("operator/", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_int)),
    Builtin_Operator("operator/", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_int)),
    Builtin_Operator("operator/", (Builtin_Type.type_ivec2, Builtin_Type.type_int, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator/", (Builtin_Type.type_ivec3, Builtin_Type.type_int, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator/", (Builtin_Type.type_ivec4, Builtin_Type.type_int, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator/", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uint)),
    Builtin_Operator("operator/", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uint)),
    Builtin_Operator("operator/", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uint)),
    Builtin_Operator("operator/", (Builtin_Type.type_uvec2, Builtin_Type.type_uint, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator/", (Builtin_Type.type_uvec3, Builtin_Type.type_uint, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator/", (Builtin_Type.type_uvec4, Builtin_Type.type_uint, Builtin_Type.type_uvec4)),

    Builtin_Operator("operator+", (Builtin_Type.type_mat2, Builtin_Type.type_mat2, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat3, Builtin_Type.type_mat3, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat4, Builtin_Type.type_mat4, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3, Builtin_Type.type_float)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat2, Builtin_Type.type_float, Builtin_Type.type_mat2)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat3, Builtin_Type.type_float, Builtin_Type.type_mat3)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat4, Builtin_Type.type_float, Builtin_Type.type_mat4)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat2x3, Builtin_Type.type_float, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat2x4, Builtin_Type.type_float, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat3x2, Builtin_Type.type_float, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat3x4, Builtin_Type.type_float, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat4x2, Builtin_Type.type_float, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat4x3, Builtin_Type.type_float, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat2, Builtin_Type.type_dmat2, Builtin_Type.type_double)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat3, Builtin_Type.type_dmat3, Builtin_Type.type_double)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat4, Builtin_Type.type_dmat4, Builtin_Type.type_double)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3, Builtin_Type.type_double)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4, Builtin_Type.type_double)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2, Builtin_Type.type_double)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4, Builtin_Type.type_double)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2, Builtin_Type.type_double)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3, Builtin_Type.type_double)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat2, Builtin_Type.type_double, Builtin_Type.type_dmat2)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat3, Builtin_Type.type_double, Builtin_Type.type_dmat3)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat4, Builtin_Type.type_double, Builtin_Type.type_dmat4)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat2x3, Builtin_Type.type_double, Builtin_Type.type_dmat2x3)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat2x4, Builtin_Type.type_double, Builtin_Type.type_dmat2x4)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat3x2, Builtin_Type.type_double, Builtin_Type.type_dmat3x2)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat3x4, Builtin_Type.type_double, Builtin_Type.type_dmat3x4)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat4x2, Builtin_Type.type_double, Builtin_Type.type_dmat4x2)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat4x3, Builtin_Type.type_double, Builtin_Type.type_dmat4x3)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat2, Builtin_Type.type_mat2, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat3, Builtin_Type.type_mat3, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat4, Builtin_Type.type_mat4, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat2, Builtin_Type.type_float, Builtin_Type.type_mat2)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat3, Builtin_Type.type_float, Builtin_Type.type_mat3)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat4, Builtin_Type.type_float, Builtin_Type.type_mat4)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat2x3, Builtin_Type.type_float, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat2x4, Builtin_Type.type_float, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat3x2, Builtin_Type.type_float, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat3x4, Builtin_Type.type_float, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat4x2, Builtin_Type.type_float, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat4x3, Builtin_Type.type_float, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat2, Builtin_Type.type_dmat2, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat3, Builtin_Type.type_dmat3, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat4, Builtin_Type.type_dmat4, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat2, Builtin_Type.type_double, Builtin_Type.type_dmat2)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat3, Builtin_Type.type_double, Builtin_Type.type_dmat3)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat4, Builtin_Type.type_double, Builtin_Type.type_dmat4)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat2x3, Builtin_Type.type_double, Builtin_Type.type_dmat2x3)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat2x4, Builtin_Type.type_double, Builtin_Type.type_dmat2x4)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat3x2, Builtin_Type.type_double, Builtin_Type.type_dmat3x2)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat3x4, Builtin_Type.type_double, Builtin_Type.type_dmat3x4)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat4x2, Builtin_Type.type_double, Builtin_Type.type_dmat4x2)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat4x3, Builtin_Type.type_double, Builtin_Type.type_dmat4x3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2, Builtin_Type.type_mat2, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3, Builtin_Type.type_mat3, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4, Builtin_Type.type_mat4, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3, Builtin_Type.type_float)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2, Builtin_Type.type_float, Builtin_Type.type_mat2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3, Builtin_Type.type_float, Builtin_Type.type_mat3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4, Builtin_Type.type_float, Builtin_Type.type_mat4)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2x3, Builtin_Type.type_float, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2x4, Builtin_Type.type_float, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3x2, Builtin_Type.type_float, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3x4, Builtin_Type.type_float, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4x2, Builtin_Type.type_float, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4x3, Builtin_Type.type_float, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat2, Builtin_Type.type_dmat2, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat3, Builtin_Type.type_dmat3, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat4, Builtin_Type.type_dmat4, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3, Builtin_Type.type_double)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat2, Builtin_Type.type_double, Builtin_Type.type_dmat2)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat3, Builtin_Type.type_double, Builtin_Type.type_dmat3)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat4, Builtin_Type.type_double, Builtin_Type.type_dmat4)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat2x3, Builtin_Type.type_double, Builtin_Type.type_dmat2x3)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat2x4, Builtin_Type.type_double, Builtin_Type.type_dmat2x4)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat3x2, Builtin_Type.type_double, Builtin_Type.type_dmat3x2)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat3x4, Builtin_Type.type_double, Builtin_Type.type_dmat3x4)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat4x2, Builtin_Type.type_double, Builtin_Type.type_dmat4x2)),
    Builtin_Operator("operator*", (Builtin_Type.type_dmat4x3, Builtin_Type.type_double, Builtin_Type.type_dmat4x3)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat2, Builtin_Type.type_mat2, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat3, Builtin_Type.type_mat3, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat4, Builtin_Type.type_mat4, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3, Builtin_Type.type_float)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat2, Builtin_Type.type_float, Builtin_Type.type_mat2)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat3, Builtin_Type.type_float, Builtin_Type.type_mat3)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat4, Builtin_Type.type_float, Builtin_Type.type_mat4)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat2x3, Builtin_Type.type_float, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat2x4, Builtin_Type.type_float, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat3x2, Builtin_Type.type_float, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat3x4, Builtin_Type.type_float, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat4x2, Builtin_Type.type_float, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat4x3, Builtin_Type.type_float, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat2, Builtin_Type.type_dmat2, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat3, Builtin_Type.type_dmat3, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat4, Builtin_Type.type_dmat4, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3, Builtin_Type.type_double)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat2, Builtin_Type.type_double, Builtin_Type.type_dmat2)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat3, Builtin_Type.type_double, Builtin_Type.type_dmat3)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat4, Builtin_Type.type_double, Builtin_Type.type_dmat4)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat2x3, Builtin_Type.type_double, Builtin_Type.type_dmat2x3)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat2x4, Builtin_Type.type_double, Builtin_Type.type_dmat2x4)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat3x2, Builtin_Type.type_double, Builtin_Type.type_dmat3x2)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat3x4, Builtin_Type.type_double, Builtin_Type.type_dmat3x4)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat4x2, Builtin_Type.type_double, Builtin_Type.type_dmat4x2)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat4x3, Builtin_Type.type_double, Builtin_Type.type_dmat4x3)),
    # Two operands are vectors of the same size.
    Builtin_Operator("operator+", (Builtin_Type.type_vec2, Builtin_Type.type_vec2, Builtin_Type.type_vec2)),
    Builtin_Operator("operator+", (Builtin_Type.type_vec3, Builtin_Type.type_vec3, Builtin_Type.type_vec3)),
    Builtin_Operator("operator+", (Builtin_Type.type_vec4, Builtin_Type.type_vec4, Builtin_Type.type_vec4)),
    Builtin_Operator("operator+", (Builtin_Type.type_dvec2, Builtin_Type.type_dvec2, Builtin_Type.type_dvec2)),
    Builtin_Operator("operator+", (Builtin_Type.type_dvec3, Builtin_Type.type_dvec3, Builtin_Type.type_dvec3)),
    Builtin_Operator("operator+", (Builtin_Type.type_dvec4, Builtin_Type.type_dvec4, Builtin_Type.type_dvec4)),
    Builtin_Operator("operator-", (Builtin_Type.type_vec2, Builtin_Type.type_vec2, Builtin_Type.type_vec2)),
    Builtin_Operator("operator-", (Builtin_Type.type_vec3, Builtin_Type.type_vec3, Builtin_Type.type_vec3)),
    Builtin_Operator("operator-", (Builtin_Type.type_vec4, Builtin_Type.type_vec4, Builtin_Type.type_vec4)),
    Builtin_Operator("operator-", (Builtin_Type.type_dvec2, Builtin_Type.type_dvec2, Builtin_Type.type_dvec2)),
    Builtin_Operator("operator-", (Builtin_Type.type_dvec3, Builtin_Type.type_dvec3, Builtin_Type.type_dvec3)),
    Builtin_Operator("operator-", (Builtin_Type.type_dvec4, Builtin_Type.type_dvec4, Builtin_Type.type_dvec4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec2, Builtin_Type.type_vec2, Builtin_Type.type_vec2)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec3, Builtin_Type.type_vec3, Builtin_Type.type_vec3)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec4, Builtin_Type.type_vec4, Builtin_Type.type_vec4)),
    Builtin_Operator("operator*", (Builtin_Type.type_dvec2, Builtin_Type.type_dvec2, Builtin_Type.type_dvec2)),
    Builtin_Operator("operator*", (Builtin_Type.type_dvec3, Builtin_Type.type_dvec3, Builtin_Type.type_dvec3)),
    Builtin_Operator("operator*", (Builtin_Type.type_dvec4, Builtin_Type.type_dvec4, Builtin_Type.type_dvec4)),
    Builtin_Operator("operator/", (Builtin_Type.type_vec2, Builtin_Type.type_vec2, Builtin_Type.type_vec2)),
    Builtin_Operator("operator/", (Builtin_Type.type_vec3, Builtin_Type.type_vec3, Builtin_Type.type_vec3)),
    Builtin_Operator("operator/", (Builtin_Type.type_vec4, Builtin_Type.type_vec4, Builtin_Type.type_vec4)),
    Builtin_Operator("operator/", (Builtin_Type.type_dvec2, Builtin_Type.type_dvec2, Builtin_Type.type_dvec2)),
    Builtin_Operator("operator/", (Builtin_Type.type_dvec3, Builtin_Type.type_dvec3, Builtin_Type.type_dvec3)),
    Builtin_Operator("operator/", (Builtin_Type.type_dvec4, Builtin_Type.type_dvec4, Builtin_Type.type_dvec4)),
    # The operator is add, subtract or divide and the operands are same-sized matrices.
    Builtin_Operator("operator+", (Builtin_Type.type_mat2, Builtin_Type.type_mat2, Builtin_Type.type_mat2)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat3, Builtin_Type.type_mat3, Builtin_Type.type_mat3)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat4, Builtin_Type.type_mat4, Builtin_Type.type_mat4)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator+", (Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat2, Builtin_Type.type_dmat2, Builtin_Type.type_dmat2)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat3, Builtin_Type.type_dmat3, Builtin_Type.type_dmat3)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat4, Builtin_Type.type_dmat4, Builtin_Type.type_dmat4)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2)),
    Builtin_Operator("operator+", (Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat2, Builtin_Type.type_mat2, Builtin_Type.type_mat2)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat3, Builtin_Type.type_mat3, Builtin_Type.type_mat3)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat4, Builtin_Type.type_mat4, Builtin_Type.type_mat4)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat2, Builtin_Type.type_dmat2, Builtin_Type.type_dmat2)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat3, Builtin_Type.type_dmat3, Builtin_Type.type_dmat3)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat4, Builtin_Type.type_dmat4, Builtin_Type.type_dmat4)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat2, Builtin_Type.type_mat2, Builtin_Type.type_mat2)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat3, Builtin_Type.type_mat3, Builtin_Type.type_mat3)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat4, Builtin_Type.type_mat4, Builtin_Type.type_mat4)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator/", (Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat2, Builtin_Type.type_dmat2, Builtin_Type.type_dmat2)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat3, Builtin_Type.type_dmat3, Builtin_Type.type_dmat3)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat4, Builtin_Type.type_dmat4, Builtin_Type.type_dmat4)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2)),
    Builtin_Operator("operator/", (Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3)),
    # The operator is multiply where both operands are matrices or one operand is a vector and the other a matrix.
    Builtin_Operator("operator*", (Builtin_Type.type_vec2, Builtin_Type.type_vec2, Builtin_Type.type_mat2)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec3, Builtin_Type.type_vec2, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec4, Builtin_Type.type_vec2, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec2, Builtin_Type.type_vec3, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec3, Builtin_Type.type_vec3, Builtin_Type.type_mat3)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec4, Builtin_Type.type_vec3, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec2, Builtin_Type.type_vec4, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec3, Builtin_Type.type_vec4, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec4, Builtin_Type.type_vec4, Builtin_Type.type_mat4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec2, Builtin_Type.type_mat2, Builtin_Type.type_vec2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2, Builtin_Type.type_mat2, Builtin_Type.type_mat2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2x3, Builtin_Type.type_mat2, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2x4, Builtin_Type.type_mat2, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec2, Builtin_Type.type_mat2x3, Builtin_Type.type_vec3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2, Builtin_Type.type_mat2x3, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3, Builtin_Type.type_mat3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x3, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec2, Builtin_Type.type_mat2x4, Builtin_Type.type_vec4)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2, Builtin_Type.type_mat2x4, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x4, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4, Builtin_Type.type_mat4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec3, Builtin_Type.type_mat3x2, Builtin_Type.type_vec2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2, Builtin_Type.type_mat2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3, Builtin_Type.type_mat3x2, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x2, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec3, Builtin_Type.type_mat3, Builtin_Type.type_vec3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3x2, Builtin_Type.type_mat3, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3, Builtin_Type.type_mat3, Builtin_Type.type_mat3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3x4, Builtin_Type.type_mat3, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec3, Builtin_Type.type_mat3x4, Builtin_Type.type_vec4)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x4, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3, Builtin_Type.type_mat3x4, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4, Builtin_Type.type_mat4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec4, Builtin_Type.type_mat4x2, Builtin_Type.type_vec2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2, Builtin_Type.type_mat2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x2, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4, Builtin_Type.type_mat4x2, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec4, Builtin_Type.type_mat4x3, Builtin_Type.type_vec3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x3, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3, Builtin_Type.type_mat3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4, Builtin_Type.type_mat4x3, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator*", (Builtin_Type.type_vec4, Builtin_Type.type_mat4, Builtin_Type.type_vec4)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4x2, Builtin_Type.type_mat4, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4x3, Builtin_Type.type_mat4, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator*", (Builtin_Type.type_mat4, Builtin_Type.type_mat4, Builtin_Type.type_mat4)),
    # The operator modulus operates on signed or unsigned integers or integer vectors.
    Builtin_Operator("operator%", (Builtin_Type.type_int, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator%", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator%", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator%", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator%", (Builtin_Type.type_uint, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator%", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator%", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator%", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uvec4)),
    # The arithmetic unary negate operates on integer or floating-point values, including vectors and matrices.
    Builtin_Operator("operator-", (Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator-", (Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator-", (Builtin_Type.type_float, Builtin_Type.type_float)),
    Builtin_Operator("operator-", (Builtin_Type.type_double, Builtin_Type.type_double)),
    Builtin_Operator("operator-", (Builtin_Type.type_vec2, Builtin_Type.type_vec2)),
    Builtin_Operator("operator-", (Builtin_Type.type_vec3, Builtin_Type.type_vec3)),
    Builtin_Operator("operator-", (Builtin_Type.type_vec4, Builtin_Type.type_vec4)),
    Builtin_Operator("operator-", (Builtin_Type.type_dvec2, Builtin_Type.type_dvec2)),
    Builtin_Operator("operator-", (Builtin_Type.type_dvec3, Builtin_Type.type_dvec3)),
    Builtin_Operator("operator-", (Builtin_Type.type_dvec4, Builtin_Type.type_dvec4)),
    Builtin_Operator("operator-", (Builtin_Type.type_bvec2, Builtin_Type.type_bvec2)),
    Builtin_Operator("operator-", (Builtin_Type.type_bvec3, Builtin_Type.type_bvec3)),
    Builtin_Operator("operator-", (Builtin_Type.type_bvec4, Builtin_Type.type_bvec4)),
    Builtin_Operator("operator-", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator-", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator-", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator-", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator-", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator-", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat2, Builtin_Type.type_mat2)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat3, Builtin_Type.type_mat3)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat4, Builtin_Type.type_mat4)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator-", (Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat2, Builtin_Type.type_dmat2)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat3, Builtin_Type.type_dmat3)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat4, Builtin_Type.type_dmat4)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2)),
    Builtin_Operator("operator-", (Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3)),
    # The relational operators greater, less, greater equal and less equal operate only on scalar integer and floating-point expressions.
    Builtin_Operator("operator>", (Builtin_Type.type_bool, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator>", (Builtin_Type.type_bool, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator>", (Builtin_Type.type_bool, Builtin_Type.type_float, Builtin_Type.type_float)),
    Builtin_Operator("operator>", (Builtin_Type.type_bool, Builtin_Type.type_double, Builtin_Type.type_double)),
    Builtin_Operator("operator>=", (Builtin_Type.type_bool, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator>=", (Builtin_Type.type_bool, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator>=", (Builtin_Type.type_bool, Builtin_Type.type_float, Builtin_Type.type_float)),
    Builtin_Operator("operator>=", (Builtin_Type.type_bool, Builtin_Type.type_double, Builtin_Type.type_double)),
    Builtin_Operator("operator<", (Builtin_Type.type_bool, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator<", (Builtin_Type.type_bool, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator<", (Builtin_Type.type_bool, Builtin_Type.type_float, Builtin_Type.type_float)),
    Builtin_Operator("operator<", (Builtin_Type.type_bool, Builtin_Type.type_double, Builtin_Type.type_double)),
    Builtin_Operator("operator<=", (Builtin_Type.type_bool, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator<=", (Builtin_Type.type_bool, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator<=", (Builtin_Type.type_bool, Builtin_Type.type_float, Builtin_Type.type_float)),
    Builtin_Operator("operator<=", (Builtin_Type.type_bool, Builtin_Type.type_double, Builtin_Type.type_double)),
    # The equal and not equal operators work on all types except opaque types or aggregates that contain opaque types.
    # We cannot generate those operators for all types, hence we only generate the builtin types overloads.
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_bool, Builtin_Type.type_bool)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_float, Builtin_Type.type_float)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_double, Builtin_Type.type_double)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_vec2, Builtin_Type.type_vec2)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_vec3, Builtin_Type.type_vec3)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_vec4, Builtin_Type.type_vec4)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_dvec2, Builtin_Type.type_dvec2)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_dvec3, Builtin_Type.type_dvec3)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_dvec4, Builtin_Type.type_dvec4)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_bvec2, Builtin_Type.type_bvec2)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_bvec3, Builtin_Type.type_bvec3)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_bvec4, Builtin_Type.type_bvec4)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_ivec2, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_ivec3, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_ivec4, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_uvec2, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_uvec3, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_uvec4, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_mat2, Builtin_Type.type_mat2)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_mat3, Builtin_Type.type_mat3)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_mat4, Builtin_Type.type_mat4)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_dmat2, Builtin_Type.type_dmat2)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_dmat3, Builtin_Type.type_dmat3)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_dmat4, Builtin_Type.type_dmat4)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2)),
    Builtin_Operator("operator==", (Builtin_Type.type_bool, Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_bool, Builtin_Type.type_bool)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_float, Builtin_Type.type_float)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_double, Builtin_Type.type_double)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_vec2, Builtin_Type.type_vec2)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_vec3, Builtin_Type.type_vec3)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_vec4, Builtin_Type.type_vec4)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_dvec2, Builtin_Type.type_dvec2)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_dvec3, Builtin_Type.type_dvec3)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_dvec4, Builtin_Type.type_dvec4)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_bvec2, Builtin_Type.type_bvec2)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_bvec3, Builtin_Type.type_bvec3)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_bvec4, Builtin_Type.type_bvec4)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_ivec2, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_ivec3, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_ivec4, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_uvec2, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_uvec3, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_uvec4, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_mat2, Builtin_Type.type_mat2)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_mat3, Builtin_Type.type_mat3)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_mat4, Builtin_Type.type_mat4)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_mat2x3, Builtin_Type.type_mat2x3)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_mat2x4, Builtin_Type.type_mat2x4)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_mat3x2, Builtin_Type.type_mat3x2)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_mat3x4, Builtin_Type.type_mat3x4)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_mat4x2, Builtin_Type.type_mat4x2)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_mat4x3, Builtin_Type.type_mat4x3)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_dmat2, Builtin_Type.type_dmat2)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_dmat3, Builtin_Type.type_dmat3)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_dmat4, Builtin_Type.type_dmat4)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_dmat2x3, Builtin_Type.type_dmat2x3)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_dmat2x4, Builtin_Type.type_dmat2x4)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_dmat3x2, Builtin_Type.type_dmat3x2)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_dmat3x4, Builtin_Type.type_dmat3x4)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_dmat4x2, Builtin_Type.type_dmat4x2)),
    Builtin_Operator("operator!=", (Builtin_Type.type_bool, Builtin_Type.type_dmat4x3, Builtin_Type.type_dmat4x3)),
    # The logical binary operators and, or and  exclusive or operate only on boolean expressions.
    Builtin_Operator("operator&&", (Builtin_Type.type_bool, Builtin_Type.type_bool, Builtin_Type.type_bool)),
    Builtin_Operator("operator||", (Builtin_Type.type_bool, Builtin_Type.type_bool, Builtin_Type.type_bool)),
    Builtin_Operator("operator^^", (Builtin_Type.type_bool, Builtin_Type.type_bool, Builtin_Type.type_bool)),
    #
    Builtin_Operator("operator!", (Builtin_Type.type_bool, Builtin_Type.type_bool)),
    #
    Builtin_Operator("operator~", (Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator~", (Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator~", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator~", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator~", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator~", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator~", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator~", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4)),
    #
    Builtin_Operator("operator<<", (Builtin_Type.type_int, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator<<", (Builtin_Type.type_int, Builtin_Type.type_int, Builtin_Type.type_uint)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uint, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uint, Builtin_Type.type_uint, Builtin_Type.type_int)),
    Builtin_Operator("operator<<", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator<<", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator<<", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_int)),
    Builtin_Operator("operator<<", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_uint)),
    Builtin_Operator("operator<<", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator<<", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator<<", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_int)),
    Builtin_Operator("operator<<", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_uint)),
    Builtin_Operator("operator<<", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator<<", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator<<", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_int)),
    Builtin_Operator("operator<<", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_uint)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_int)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uint)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_int)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uint)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_int)),
    Builtin_Operator("operator<<", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uint)),
    #
    Builtin_Operator("operator&", (Builtin_Type.type_int, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator&", (Builtin_Type.type_uint, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator&", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator&", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_int)),
    Builtin_Operator("operator&", (Builtin_Type.type_ivec2, Builtin_Type.type_int, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator&", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator&", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_int)),
    Builtin_Operator("operator&", (Builtin_Type.type_ivec3, Builtin_Type.type_int, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator&", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator&", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_int)),
    Builtin_Operator("operator&", (Builtin_Type.type_ivec4, Builtin_Type.type_int, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator&", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator&", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uint)),
    Builtin_Operator("operator&", (Builtin_Type.type_uvec2, Builtin_Type.type_uint, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator&", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator&", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uint)),
    Builtin_Operator("operator&", (Builtin_Type.type_uvec3, Builtin_Type.type_uint, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator&", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator&", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uint)),
    Builtin_Operator("operator&", (Builtin_Type.type_uvec4, Builtin_Type.type_uint, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator|", (Builtin_Type.type_int, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator|", (Builtin_Type.type_uint, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator|", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator|", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_int)),
    Builtin_Operator("operator|", (Builtin_Type.type_ivec2, Builtin_Type.type_int, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator|", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator|", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_int)),
    Builtin_Operator("operator|", (Builtin_Type.type_ivec3, Builtin_Type.type_int, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator|", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator|", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_int)),
    Builtin_Operator("operator|", (Builtin_Type.type_ivec4, Builtin_Type.type_int, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator|", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator|", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uint)),
    Builtin_Operator("operator|", (Builtin_Type.type_uvec2, Builtin_Type.type_uint, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator|", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator|", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uint)),
    Builtin_Operator("operator|", (Builtin_Type.type_uvec3, Builtin_Type.type_uint, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator|", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator|", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uint)),
    Builtin_Operator("operator|", (Builtin_Type.type_uvec4, Builtin_Type.type_uint, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator^", (Builtin_Type.type_int, Builtin_Type.type_int, Builtin_Type.type_int)),
    Builtin_Operator("operator^", (Builtin_Type.type_uint, Builtin_Type.type_uint, Builtin_Type.type_uint)),
    Builtin_Operator("operator^", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator^", (Builtin_Type.type_ivec2, Builtin_Type.type_ivec2, Builtin_Type.type_int)),
    Builtin_Operator("operator^", (Builtin_Type.type_ivec2, Builtin_Type.type_int, Builtin_Type.type_ivec2)),
    Builtin_Operator("operator^", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator^", (Builtin_Type.type_ivec3, Builtin_Type.type_ivec3, Builtin_Type.type_int)),
    Builtin_Operator("operator^", (Builtin_Type.type_ivec3, Builtin_Type.type_int, Builtin_Type.type_ivec3)),
    Builtin_Operator("operator^", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator^", (Builtin_Type.type_ivec4, Builtin_Type.type_ivec4, Builtin_Type.type_int)),
    Builtin_Operator("operator^", (Builtin_Type.type_ivec4, Builtin_Type.type_int, Builtin_Type.type_ivec4)),
    Builtin_Operator("operator^", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator^", (Builtin_Type.type_uvec2, Builtin_Type.type_uvec2, Builtin_Type.type_uint)),
    Builtin_Operator("operator^", (Builtin_Type.type_uvec2, Builtin_Type.type_uint, Builtin_Type.type_uvec2)),
    Builtin_Operator("operator^", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator^", (Builtin_Type.type_uvec3, Builtin_Type.type_uvec3, Builtin_Type.type_uint)),
    Builtin_Operator("operator^", (Builtin_Type.type_uvec3, Builtin_Type.type_uint, Builtin_Type.type_uvec3)),
    Builtin_Operator("operator^", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uvec4)),
    Builtin_Operator("operator^", (Builtin_Type.type_uvec4, Builtin_Type.type_uvec4, Builtin_Type.type_uint)),
    Builtin_Operator("operator^", (Builtin_Type.type_uvec4, Builtin_Type.type_uint, Builtin_Type.type_uvec4)),
)
