#include <ast.hpp>

namespace vush {
    bool is_opaque_type(Type const& type) {
        ANTON_ASSERT(type.node_type == AST_Node_Type::builtin_type || type.node_type == AST_Node_Type::user_defined_type ||
                         type.node_type == AST_Node_Type::array_type,
                     u8"unknown ast node type");
        if(type.node_type == AST_Node_Type::builtin_type) {
            Builtin_Type const& t = static_cast<Builtin_Type const&>(type);
            return is_opaque_type(t.type);
        } else if(type.node_type == AST_Node_Type::user_defined_type) {
            return false;
        } else {
            Array_Type const& t = static_cast<Array_Type const&>(type);
            return is_opaque_type(*t.base);
        }
    }

    anton::String stringify_type(Type const& type) {
        ANTON_ASSERT(type.node_type == AST_Node_Type::builtin_type || type.node_type == AST_Node_Type::user_defined_type ||
                         type.node_type == AST_Node_Type::array_type,
                     u8"unknown ast node type");
        if(type.node_type == AST_Node_Type::builtin_type) {
            Builtin_Type const& t = static_cast<Builtin_Type const&>(type);
            anton::String_View sv = stringify(t.type);
            return anton::String(sv);
        } else if(type.node_type == AST_Node_Type::user_defined_type) {
            User_Defined_Type const& t = static_cast<User_Defined_Type const&>(type);
            return t.name;
        } else {
            Array_Type const& t = static_cast<Array_Type const&>(type);
            anton::String str = stringify_type(*t.base);
            str += u8"[";
            if(t.size) {
                str += t.size->value;
            }
            str += u8"]";
            return str;
        }
    }

    anton::Optional<Builtin_GLSL_Type> enumify_builtin_glsl_type(anton::String_View const type) {
        static constexpr anton::String_View builtin_types_strings[] = {
            "void",
            "bool",
            "int",
            "uint",
            "float",
            "double",
            "vec2",
            "vec3",
            "vec4",
            "dvec2",
            "dvec3",
            "dvec4",
            "bvec2",
            "bvec3",
            "bvec4",
            "ivec2",
            "ivec3",
            "ivec4",
            "uvec2",
            "uvec3",
            "uvec4",
            "mat2",
            "mat2x2",
            "mat3",
            "mat3x3",
            "mat4",
            "mat4x4",
            "mat2x3",
            "mat2x4",
            "mat3x2",
            "mat3x4",
            "mat4x2",
            "mat4x3",
            "dmat2",
            "dmat2x2",
            "dmat3",
            "dmat3x3",
            "dmat4",
            "dmat4x4",
            "dmat2x3",
            "dmat2x4",
            "dmat3x2",
            "dmat3x4",
            "dmat4x2",
            "dmat4x3",
            "sampler1D",
            "texture1D",
            "image1D",
            "sampler1DShadow",
            "sampler1DArray",
            "texture1DArray",
            "image1DArray",
            "sampler1DArrayShadow",
            "sampler2D",
            "texture2D",
            "image2D",
            "sampler2DShadow",
            "sampler2DArray",
            "texture2DArray",
            "image2DArray",
            "sampler2DArrayShadow",
            "sampler2DMS",
            "texture2DMS",
            "image2DMS",
            "sampler2DMSArray",
            "texture2DMSArray",
            "image2DMSArray",
            "sampler2DRect",
            "texture2DRect",
            "image2DRect",
            "sampler2DRectShadow",
            "sampler3D",
            "texture3D",
            "image3D",
            "samplerCube",
            "textureCube",
            "imageCube",
            "samplerCubeShadow",
            "samplerCubeArray",
            "textureCubeArray",
            "imageCubeArray",
            "samplerCubeArrayShadow",
            "samplerBuffer",
            "textureBuffer",
            "imageBuffer",
            "subpassInput",
            "subpassInputMS",
            "isampler1D",
            "itexture1D",
            "iimage1D",
            "isampler1DArray",
            "itexture1DArray",
            "iimage1DArray",
            "isampler2D",
            "itexture2D",
            "iimage2D",
            "isampler2DArray",
            "itexture2DArray",
            "iimage2DArray",
            "isampler2DMS",
            "itexture2DMS",
            "iimage2DMS",
            "isampler2DMSArray",
            "itexture2DMSArray",
            "iimage2DMSArray",
            "isampler2DRect",
            "itexture2DRect",
            "iimage2DRect",
            "isampler3D",
            "itexture3D",
            "iimage3D",
            "isamplerCube",
            "itextureCube",
            "iimageCube",
            "isamplerCubeArray",
            "itextureCubeArray",
            "iimageCubeArray",
            "isamplerBuffer",
            "itextureBuffer",
            "iimageBuffer",
            "isubpassInput",
            "isubpassInputMS",
            "usampler1D",
            "utexture1D",
            "uimage1D",
            "usampler1DArray",
            "utexture1DArray",
            "uimage1DArray",
            "usampler2D",
            "utexture2D",
            "uimage2D",
            "usampler2DArray",
            "utexture2DArray",
            "uimage2DArray",
            "usampler2DMS",
            "utexture2DMS",
            "uimage2DMS",
            "usampler2DMSArray",
            "utexture2DMSArray",
            "uimage2DMSArray",
            "usampler2DRect",
            "utexture2DRect",
            "uimage2DRect",
            "usampler3D",
            "utexture3D",
            "uimage3D",
            "usamplerCube",
            "utextureCube",
            "uimageCube",
            "usamplerCubeArray",
            "utextureCubeArray",
            "uimageCubeArray",
            "usamplerBuffer",
            "utextureBuffer",
            "uimageBuffer",
            "usubpassInput",
            "usubpassInputMS",
            "sampler",
            "samplerShadow",
        };

        static constexpr Builtin_GLSL_Type builtin_types[] = {
            Builtin_GLSL_Type::glsl_void,
            Builtin_GLSL_Type::glsl_bool,
            Builtin_GLSL_Type::glsl_int,
            Builtin_GLSL_Type::glsl_uint,
            Builtin_GLSL_Type::glsl_float,
            Builtin_GLSL_Type::glsl_double,
            Builtin_GLSL_Type::glsl_vec2,
            Builtin_GLSL_Type::glsl_vec3,
            Builtin_GLSL_Type::glsl_vec4,
            Builtin_GLSL_Type::glsl_dvec2,
            Builtin_GLSL_Type::glsl_dvec3,
            Builtin_GLSL_Type::glsl_dvec4,
            Builtin_GLSL_Type::glsl_bvec2,
            Builtin_GLSL_Type::glsl_bvec3,
            Builtin_GLSL_Type::glsl_bvec4,
            Builtin_GLSL_Type::glsl_ivec2,
            Builtin_GLSL_Type::glsl_ivec3,
            Builtin_GLSL_Type::glsl_ivec4,
            Builtin_GLSL_Type::glsl_uvec2,
            Builtin_GLSL_Type::glsl_uvec3,
            Builtin_GLSL_Type::glsl_uvec4,
            Builtin_GLSL_Type::glsl_mat2,
            Builtin_GLSL_Type::glsl_mat2,
            Builtin_GLSL_Type::glsl_mat3,
            Builtin_GLSL_Type::glsl_mat3,
            Builtin_GLSL_Type::glsl_mat4,
            Builtin_GLSL_Type::glsl_mat4,
            Builtin_GLSL_Type::glsl_mat2x3,
            Builtin_GLSL_Type::glsl_mat2x4,
            Builtin_GLSL_Type::glsl_mat3x2,
            Builtin_GLSL_Type::glsl_mat3x4,
            Builtin_GLSL_Type::glsl_mat4x2,
            Builtin_GLSL_Type::glsl_mat4x3,
            Builtin_GLSL_Type::glsl_dmat2,
            Builtin_GLSL_Type::glsl_dmat2,
            Builtin_GLSL_Type::glsl_dmat3,
            Builtin_GLSL_Type::glsl_dmat3,
            Builtin_GLSL_Type::glsl_dmat4,
            Builtin_GLSL_Type::glsl_dmat4,
            Builtin_GLSL_Type::glsl_dmat2x3,
            Builtin_GLSL_Type::glsl_dmat2x4,
            Builtin_GLSL_Type::glsl_dmat3x2,
            Builtin_GLSL_Type::glsl_dmat3x4,
            Builtin_GLSL_Type::glsl_dmat4x2,
            Builtin_GLSL_Type::glsl_dmat4x3,
            Builtin_GLSL_Type::glsl_sampler1D,
            Builtin_GLSL_Type::glsl_texture1D,
            Builtin_GLSL_Type::glsl_image1D,
            Builtin_GLSL_Type::glsl_sampler1DShadow,
            Builtin_GLSL_Type::glsl_sampler1DArray,
            Builtin_GLSL_Type::glsl_texture1DArray,
            Builtin_GLSL_Type::glsl_image1DArray,
            Builtin_GLSL_Type::glsl_sampler1DArrayShadow,
            Builtin_GLSL_Type::glsl_sampler2D,
            Builtin_GLSL_Type::glsl_texture2D,
            Builtin_GLSL_Type::glsl_image2D,
            Builtin_GLSL_Type::glsl_sampler2DShadow,
            Builtin_GLSL_Type::glsl_sampler2DArray,
            Builtin_GLSL_Type::glsl_texture2DArray,
            Builtin_GLSL_Type::glsl_image2DArray,
            Builtin_GLSL_Type::glsl_sampler2DArrayShadow,
            Builtin_GLSL_Type::glsl_sampler2DMS,
            Builtin_GLSL_Type::glsl_texture2DMS,
            Builtin_GLSL_Type::glsl_image2DMS,
            Builtin_GLSL_Type::glsl_sampler2DMSArray,
            Builtin_GLSL_Type::glsl_texture2DMSArray,
            Builtin_GLSL_Type::glsl_image2DMSArray,
            Builtin_GLSL_Type::glsl_sampler2DRect,
            Builtin_GLSL_Type::glsl_texture2DRect,
            Builtin_GLSL_Type::glsl_image2DRect,
            Builtin_GLSL_Type::glsl_sampler2DRectShadow,
            Builtin_GLSL_Type::glsl_sampler3D,
            Builtin_GLSL_Type::glsl_texture3D,
            Builtin_GLSL_Type::glsl_image3D,
            Builtin_GLSL_Type::glsl_samplerCube,
            Builtin_GLSL_Type::glsl_textureCube,
            Builtin_GLSL_Type::glsl_imageCube,
            Builtin_GLSL_Type::glsl_samplerCubeShadow,
            Builtin_GLSL_Type::glsl_samplerCubeArray,
            Builtin_GLSL_Type::glsl_textureCubeArray,
            Builtin_GLSL_Type::glsl_imageCubeArray,
            Builtin_GLSL_Type::glsl_samplerCubeArrayShadow,
            Builtin_GLSL_Type::glsl_samplerBuffer,
            Builtin_GLSL_Type::glsl_textureBuffer,
            Builtin_GLSL_Type::glsl_imageBuffer,
            Builtin_GLSL_Type::glsl_subpassInput,
            Builtin_GLSL_Type::glsl_subpassInputMS,
            Builtin_GLSL_Type::glsl_isampler1D,
            Builtin_GLSL_Type::glsl_itexture1D,
            Builtin_GLSL_Type::glsl_iimage1D,
            Builtin_GLSL_Type::glsl_isampler1DArray,
            Builtin_GLSL_Type::glsl_itexture1DArray,
            Builtin_GLSL_Type::glsl_iimage1DArray,
            Builtin_GLSL_Type::glsl_isampler2D,
            Builtin_GLSL_Type::glsl_itexture2D,
            Builtin_GLSL_Type::glsl_iimage2D,
            Builtin_GLSL_Type::glsl_isampler2DArray,
            Builtin_GLSL_Type::glsl_itexture2DArray,
            Builtin_GLSL_Type::glsl_iimage2DArray,
            Builtin_GLSL_Type::glsl_isampler2DMS,
            Builtin_GLSL_Type::glsl_itexture2DMS,
            Builtin_GLSL_Type::glsl_iimage2DMS,
            Builtin_GLSL_Type::glsl_isampler2DMSArray,
            Builtin_GLSL_Type::glsl_itexture2DMSArray,
            Builtin_GLSL_Type::glsl_iimage2DMSArray,
            Builtin_GLSL_Type::glsl_isampler2DRect,
            Builtin_GLSL_Type::glsl_itexture2DRect,
            Builtin_GLSL_Type::glsl_iimage2DRect,
            Builtin_GLSL_Type::glsl_isampler3D,
            Builtin_GLSL_Type::glsl_itexture3D,
            Builtin_GLSL_Type::glsl_iimage3D,
            Builtin_GLSL_Type::glsl_isamplerCube,
            Builtin_GLSL_Type::glsl_itextureCube,
            Builtin_GLSL_Type::glsl_iimageCube,
            Builtin_GLSL_Type::glsl_isamplerCubeArray,
            Builtin_GLSL_Type::glsl_itextureCubeArray,
            Builtin_GLSL_Type::glsl_iimageCubeArray,
            Builtin_GLSL_Type::glsl_isamplerBuffer,
            Builtin_GLSL_Type::glsl_itextureBuffer,
            Builtin_GLSL_Type::glsl_iimageBuffer,
            Builtin_GLSL_Type::glsl_isubpassInput,
            Builtin_GLSL_Type::glsl_isubpassInputMS,
            Builtin_GLSL_Type::glsl_usampler1D,
            Builtin_GLSL_Type::glsl_utexture1D,
            Builtin_GLSL_Type::glsl_uimage1D,
            Builtin_GLSL_Type::glsl_usampler1DArray,
            Builtin_GLSL_Type::glsl_utexture1DArray,
            Builtin_GLSL_Type::glsl_uimage1DArray,
            Builtin_GLSL_Type::glsl_usampler2D,
            Builtin_GLSL_Type::glsl_utexture2D,
            Builtin_GLSL_Type::glsl_uimage2D,
            Builtin_GLSL_Type::glsl_usampler2DArray,
            Builtin_GLSL_Type::glsl_utexture2DArray,
            Builtin_GLSL_Type::glsl_uimage2DArray,
            Builtin_GLSL_Type::glsl_usampler2DMS,
            Builtin_GLSL_Type::glsl_utexture2DMS,
            Builtin_GLSL_Type::glsl_uimage2DMS,
            Builtin_GLSL_Type::glsl_usampler2DMSArray,
            Builtin_GLSL_Type::glsl_utexture2DMSArray,
            Builtin_GLSL_Type::glsl_uimage2DMSArray,
            Builtin_GLSL_Type::glsl_usampler2DRect,
            Builtin_GLSL_Type::glsl_utexture2DRect,
            Builtin_GLSL_Type::glsl_uimage2DRect,
            Builtin_GLSL_Type::glsl_usampler3D,
            Builtin_GLSL_Type::glsl_utexture3D,
            Builtin_GLSL_Type::glsl_uimage3D,
            Builtin_GLSL_Type::glsl_usamplerCube,
            Builtin_GLSL_Type::glsl_utextureCube,
            Builtin_GLSL_Type::glsl_uimageCube,
            Builtin_GLSL_Type::glsl_usamplerCubeArray,
            Builtin_GLSL_Type::glsl_utextureCubeArray,
            Builtin_GLSL_Type::glsl_uimageCubeArray,
            Builtin_GLSL_Type::glsl_usamplerBuffer,
            Builtin_GLSL_Type::glsl_utextureBuffer,
            Builtin_GLSL_Type::glsl_uimageBuffer,
            Builtin_GLSL_Type::glsl_usubpassInput,
            Builtin_GLSL_Type::glsl_usubpassInputMS,
            Builtin_GLSL_Type::glsl_sampler,
            Builtin_GLSL_Type::glsl_samplerShadow,
        };

        constexpr i64 array_size = sizeof(builtin_types_strings) / sizeof(anton::String_View);
        for(i64 i = 0; i < array_size; ++i) {
            if(type == builtin_types_strings[i]) {
                return builtin_types[i];
            }
        }

        return anton::null_optional;
    }

    bool is_unsized_array(Type const& type) {
        return type.node_type == AST_Node_Type::array_type && !static_cast<Array_Type const&>(type).size;
    }

    bool is_sized_array(Type const& type) {
        return type.node_type == AST_Node_Type::array_type && static_cast<Array_Type const&>(type).size;
    }
} // namespace vush
